### ISSUE TITLE
CloudFormation yaml as output?

### ISSUE THREAD

**Issue by TryTryAgain** [percolate/ec2-security-groups-dumper#30]
I've seen other threads (Reddit, etc.) talking about having `ec2-security-groups-dumper` export to usable CloudFormation templates (yaml). This would be extremely helpful. 

Are there other solutions out there using the output of `ec2-security-groups-dumper` in csv or json as valid input to easily create a new security group using the dumped output?

**Comment by lra** [comment]
I'm not aware of any, this tool has been built before terraform was a thing, and most (included us) switched to terraform.

**Comment by TryTryAgain** [comment]
That's fair enough, makes sense. Because Terraform's `import` isn't the easiest/prettiest to work with, I think I may take `ec2-security-groups-dumper` output and generate terraform code. I really do like the ease of dumping this tool provides.

**Comment by lra** [comment]
Oh sorry, I missed the fact that now we also have `awscli` where you can dump everything from their API in json.
