### ISSUE TITLE
Unable to change AWS region

### ISSUE THREAD

**Issue by sh1n0b1** [percolate/ec2-security-groups-dumper#4]
I'm having difficult changing the AWS region where the security groups are being pull. I tired setting the region in ~/.aws/config and ~/.boto, but it only pull the security groups from us-east-1.

**Comment by lra** [comment]
I have this in my `.boto`:

```ini
[Boto]
ec2_region_name = us-west-1
ec2_region_endpoint = ec2.us-west-1.amazonaws.com
```

Try it?

**Comment by sh1n0b1** [comment]
Yup, that works! It looks like you have to specify a endpoint uri and the endpoint uri is not the uri of the AWS console. Thanks for the quick reply.
