### ISSUE TITLE
Issue with CSV - Missing column data for rules that have "rules_grants_group_id" populated

### ISSUE THREAD

**Issue by richrepko** [percolate/ec2-security-groups-dumper#9]
First off, thank you for hard work on this great tool!
I am running into an issue with csv output for rules that have a security group defined in "rules_grants_group_id" . Data for the "rules_ip_protocol" column is missing in the mentioned scenario.

**Comment by lra** [comment]
do you have a way to reproduce the problem?

**Comment by richrepko** [comment]
I was able to reproduce the issue by adding a rule to grant "All Traffic" to another security group.

**Comment by lra** [comment]
Sorry still can't reproduce:

![screen shot 2016-11-23 at 9 15 30 am](https://cloud.githubusercontent.com/assets/122286/20571704/72afc01c-b15d-11e6-82b9-adb5f70abbfa.png)

And I get:
```
$ ec2-security-groups-dumper --csv|grep "rules_ip_protocol\|lolo"
id,name,description,rules_ip_protocol,rules_from_port,rules_to_port,rules_grants_group_id,rules_grants_name,rules_grants_cidr_ip
sg-ae375fea,test,test lolo,icmp,-1,-1,sg-0383,vpn,
sg-ae375fea,test,test lolo,tcp,0,65535,sg-3d7d,vault,
sg-ae375fea,test,test lolo,udp,0,65535,,,0.0.0.0/0
```

I get a protocol on every row

**Comment by richrepko** [comment]
Try with "All Traffic" type as shown in screenshot

![image](https://cloud.githubusercontent.com/assets/10713700/20572284/e3aaf776-b178-11e6-8865-8f802c893d6d.png)

**Comment by lra** [comment]
I don't have such an option:
![screen shot 2016-11-23 at 10 20 58 am](https://cloud.githubusercontent.com/assets/122286/20573849/990f10d8-b166-11e6-9621-5d79d7f17082.png)

Is it a VPC security group?

Also, if all traffic is allows, I find it useful to leave the field empty, what would you like to see in it? a [magic string](https://en.wikipedia.org/wiki/Magic_string)? ;)

**Comment by richrepko** [comment]
Yes, it is a EC2-VPC security group.
![image](https://cloud.githubusercontent.com/assets/10713700/20574548/fdbd8660-b182-11e6-92c0-9dee11c2ed9f.png)

For instances where all traffic is allowed it should show as "-1". For IP address sources, it shows the correct value.

```
$ ec2-security-groups-dumper --csv  |grep "rules_ip_protocol\|sg-2cad3a51"
id,name,description,rules_ip_protocol,rules_from_port,rules_to_port,rules_grants_group_id,rules_grants_name,rules_grants_cidr_ip
sg-2cad3a51,Test Security group2,test,,,,sg-2cad3a51,,
sg-2cad3a51,Test Security group2,test,-1,,,,,0.0.0.0/0
```

![image](https://cloud.githubusercontent.com/assets/10713700/20574697/d909e84e-b183-11e6-8acf-ad3e7526fe56.png)
